-- MySQL Script generated by MySQL Workbench
-- Mon Sep 18 13:00:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';\

-- -----------------------------------------------------
-- Schema sonydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sonydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sonydb` DEFAULT CHARACTER SET utf8 ;\
USE `sonydb` ;\

-- -----------------------------------------------------
-- Table `sonydb`.`TBL_XS_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sonydb`.`TBL_XS_USERS` (
  `ID` VARCHAR(128) NOT NULL,
  `NAME` VARCHAR(128) NOT NULL COMMENT '昵称',
  `BIRTHDAY` DATE NULL COMMENT '出生日期',
  `PERSONAL_SIGN` VARCHAR(256) NULL COMMENT '个性签名',
  `PHOTO` VARCHAR(128) NULL COMMENT '头像',
  `LEVEL` INT NULL COMMENT '等级',
  `KEEP_BOOK` INT NULL COMMENT '藏书数',
  `TBL_XS_USERScol` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;\


-- -----------------------------------------------------
-- Table `sonydb`.`TBL_XS_BOOKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sonydb`.`TBL_XS_BOOKS` (
  `ID` VARCHAR(128) NOT NULL,
  `NAME` VARCHAR(128) NOT NULL COMMENT '书名',
  `AUTHOR` VARCHAR(128) NULL COMMENT '作者',
  `PUBLISHING` VARCHAR(128) NULL COMMENT '出版社',
  `OWNER` VARCHAR(128) NULL COMMENT '发布人',
  `TAGS` VARCHAR(256) NULL COMMENT '标签',
  `PRICE` FLOAT NULL COMMENT '原价',
  `DISCOUNT_PRICE` FLOAT NULL COMMENT '折扣价',
  `IMG` VARCHAR(256) NULL COMMENT '图片',
  `NEW_DEGREE` FLOAT NULL COMMENT '新旧程度',
  `ISBN` VARCHAR(45) NULL,
  `PUBLISH_TIME` DATE NULL COMMENT '发布时间',
  `PERMISSION` INT NULL COMMENT '权限，取public，private（个人），protected(朋友可见)',
  PRIMARY KEY (`ID`),
  INDEX `OWNER_idx` (`OWNER` ASC),
  CONSTRAINT `OWNER`
    FOREIGN KEY (`OWNER`)
    REFERENCES `sonydb`.`TBL_XS_USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;\


-- -----------------------------------------------------
-- Table `sonydb`.`TBL_XS_BOOK_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sonydb`.`TBL_XS_BOOK_TYPE` (
  `ID` VARCHAR(128) NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTIOIN` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;\


-- -----------------------------------------------------
-- Table `sonydb`.`TBL_XS_BOOK_HALL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sonydb`.`TBL_XS_BOOK_HALL` (
  `ID` VARCHAR(128) NOT NULL,
  `NAME` VARCHAR(128) NULL COMMENT '书堂名称',
  `TAGS` VARCHAR(256) NULL COMMENT '书堂标签',
  `DESCRIPTION` VARCHAR(1024) NULL COMMENT '书堂描述信息',
  `ALIVE_COUNT` INT NULL COMMENT '人气',
  `OWNER` VARCHAR(128) NULL COMMENT '创建人',
  `LEVEL` INT NULL COMMENT '等级',
  `IMG` VARCHAR(128) NULL COMMENT '堂图',
  PRIMARY KEY (`ID`),
  INDEX `bookHall_owner_user_id_idx` (`OWNER` ASC),
  CONSTRAINT `bookHall_owner_user_id`
    FOREIGN KEY (`OWNER`)
    REFERENCES `sonydb`.`TBL_XS_USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;\


-- -----------------------------------------------------
-- Table `sonydb`.`TBL_XS_BH_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sonydb`.`TBL_XS_BH_USERS` (
  `HALL_ID` VARCHAR(128) NOT NULL,
  `USER_ID` VARCHAR(128) NULL,
  INDEX `booHallUser_ID_User_ID_idx` (`USER_ID` ASC),
  INDEX `booHallUser_hallId_BookHall_ID_idx` (`HALL_ID` ASC),
  CONSTRAINT `booHallUser_ID_User_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `sonydb`.`TBL_XS_USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `booHallUser_hallId_BookHall_ID`
    FOREIGN KEY (`HALL_ID`)
    REFERENCES `sonydb`.`TBL_XS_BOOK_HALL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;\


-- -----------------------------------------------------
-- Table `sonydb`.`TBL_XS_BH_BOOKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sonydb`.`TBL_XS_BH_BOOKS` (
  `BOOK_ID` VARCHAR(128) NOT NULL,
  `BH_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BOOK_ID`, `BH_ID`))
ENGINE = InnoDB;\


SET SQL_MODE=@OLD_SQL_MODE;\
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;\
